[package]
name = "astrealrblx/roactive"
description = "Lightweight and fast reactive state library"
license = "MIT"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["examples"]